# Generated by Django 5.2.9 on 2026-03-09 05:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workflows', '0002_explorationphasedata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptualCanvas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when this record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when this record was last modified.')),
                ('name', models.CharField(max_length=24)),
                ('workflow', models.ForeignKey(help_text='The ID of the user owning this workflow.', on_delete=django.db.models.deletion.CASCADE, to='workflows.researchworkflow')),
            ],
            options={
                'verbose_name': 'Conceptual Canvas',
                'verbose_name_plural': 'Conceptual Canvases',
            },
        ),
        migrations.CreateModel(
            name='CanvasNodeRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when this record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when this record was last modified.')),
                ('x', models.FloatField(default=0.0, help_text='Horizontal coordinate on the canvas.')),
                ('y', models.FloatField(default=0.0, help_text='Vertical coordinate on the canvas.')),
                ('status', models.CharField(choices=[('USER_DRAFT', 'User Draft'), ('AI_EXTRACTED', 'AI Extracted'), ('LOCKED', 'Locked'), ('ON_HOLD', 'On Hold'), ('ARCHIVED', 'Archived')], default='AI_EXTRACTED', max_length=20)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvases.conceptualcanvas')),
            ],
            options={
                'verbose_name': 'Canvas Node Relation',
                'verbose_name_plural': 'Canvas Node Relations',
            },
        ),
        migrations.CreateModel(
            name='ConceptualNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when this record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when this record was last modified.')),
                ('label', models.CharField(max_length=500)),
                ('node_type', models.CharField(choices=[('FOCUS', 'Focus'), ('RESOURCE', 'Resource'), ('CONCEPT', 'Concept'), ('INSIGHT', 'Insight'), ('QUERY', 'Query'), ('GROUP', 'Group'), ('NAVIGATION', 'Navigation')], max_length=20)),
                ('groundedness', models.IntegerField(default=5)),
                ('solidity', models.CharField(choices=[('SOLID', 'Solid'), ('PULSING', 'Pulsing'), ('DIMMED', 'Dimmed')], default='PULSING', max_length=20)),
                ('object_id', models.UUIDField(help_text='The UUID of the specific owner instance.')),
                ('canvases', models.ManyToManyField(related_name='node', through='canvases.CanvasNodeRelation', to='canvases.conceptualcanvas')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('workflow', models.ForeignKey(help_text='Foreign key linking the message to the parent research workflow session.', on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='workflows.researchworkflow')),
            ],
            options={
                'verbose_name': 'Conceptual Node',
                'verbose_name_plural': 'Conceptual Nodes',
            },
        ),
        migrations.AddField(
            model_name='conceptualcanvas',
            name='nodes',
            field=models.ManyToManyField(related_name='canvas', through='canvases.CanvasNodeRelation', to='canvases.conceptualnode'),
        ),
        migrations.AddField(
            model_name='canvasnoderelation',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvases.conceptualnode'),
        ),
    ]
