# Generated by Django 5.2.9 on 2026-01-20 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canvasnoderelation',
            old_name='canvases',
            new_name='canvas',
        ),
        migrations.RenameField(
            model_name='canvasnoderelation',
            old_name='nodes',
            new_name='node',
        ),
    ]
