# Generated by Django 6.0.5 on 2026-05-14 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptualedge',
            name='edge_type',
            field=models.CharField(choices=[('VALIDATES', 'Validates (Strong support)'), ('CONSTRAINS', 'Constrains (Restriction)'), ('TRIGGERS', 'Triggers (Causal/Sequential)'), ('REF', 'Reference (Weak association)'), ('LINK', 'Link (Structural connection)')], default='REF', max_length=20),
        ),
        migrations.AddField(
            model_name='conceptualedge',
            name='evidence',
            field=models.TextField(blank=True, help_text='Logical justification for this link, crucial for Agentic Audit.', null=True),
        ),
        migrations.AddField(
            model_name='conceptualedge',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conceptualedge',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Scenario-specific data like timestamps, confidence scores, etc.'),
        ),
        migrations.AddField(
            model_name='conceptualedge',
            name='rationale',
            field=models.TextField(blank=True, help_text="AI's reasoning behind establishing this connection.", null=True),
        ),
        migrations.AddField(
            model_name='conceptualnode',
            name='anchor',
            field=models.ForeignKey(blank=True, help_text='Parent node for growth tracking/hierarchy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descendants', to='canvases.conceptualnode'),
        ),
        migrations.AddField(
            model_name='conceptualnode',
            name='content',
            field=models.TextField(blank=True, help_text='Detailed snippet or content description.', null=True),
        ),
        migrations.AddField(
            model_name='conceptualnode',
            name='rationale',
            field=models.TextField(blank=True, help_text="AI's justification or reasoning for this node.", null=True),
        ),
        migrations.AddField(
            model_name='conceptualnode',
            name='source_ref',
            field=models.CharField(blank=True, help_text='Grounding reference URL or document ID.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='conceptualedge',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='canvases.conceptualnode'),
        ),
        migrations.AlterField(
            model_name='conceptualedge',
            name='source_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='conceptualedge',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='canvases.conceptualnode'),
        ),
        migrations.AlterField(
            model_name='conceptualedge',
            name='target_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='conceptualedge',
            name='weight',
            field=models.FloatField(default=1.0, help_text='Strength of the relationship.'),
        ),
        migrations.AlterField(
            model_name='conceptualnode',
            name='groundedness',
            field=models.IntegerField(default=5, help_text='Health Score (0-10). Values < 4 trigger visual alarm in frontend.'),
        ),
        migrations.AlterField(
            model_name='conceptualnode',
            name='node_type',
            field=models.CharField(choices=[('EVENT', 'Event (Objective data points)'), ('OUTCOME', 'Outcome (Final results / North Star)'), ('BOUNDARY', 'Boundary (Constraints / Scope)'), ('ENTITY', 'Entity (Subjects / Tools)'), ('FOCUS', 'Focus (Focal point of view)'), ('RESOURCE', 'Resource (External evidence items)'), ('CONCEPT', 'Concept (Logical bridges)'), ('INSIGHT', 'Insight (AI/Human Synthesis)'), ('QUERY', 'Query (Research gaps)'), ('NAVIGATION', 'Navigation (Portal for View transitions)'), ('GROUP', 'Group (Container boundaries)')], default='CONCEPT', max_length=20),
        ),
        migrations.AlterField(
            model_name='conceptualnode',
            name='solidity',
            field=models.CharField(choices=[('SOLID', 'Solid (Evidence-backed)'), ('PULSING', 'Pulsing (Hypothesis / Shadow)'), ('DIMMED', 'Dimmed (Inbox / Placeholder)')], default='PULSING', max_length=20),
        ),
    ]
