# Generated by Django 5.2.9 on 2026-03-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canvasnoderelation',
            name='anchor_id',
        ),
        migrations.RemoveField(
            model_name='conceptualedge',
            name='workflow',
        ),
        migrations.AddConstraint(
            model_name='conceptualedge',
            constraint=models.UniqueConstraint(fields=('source', 'target', 'canvas'), name='unique_conceptual_edge_per_canvas'),
        ),
    ]
