# Generated by Django 6.0.5 on 2026-05-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0002_conceptualedge_edge_type_conceptualedge_evidence_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conceptualedge',
            name='unique_conceptual_edge_per_canvas',
        ),
        migrations.AddConstraint(
            model_name='conceptualedge',
            constraint=models.UniqueConstraint(fields=('source', 'edge_type', 'target', 'canvas'), name='unique_conceptual_edge_per_canvas'),
        ),
    ]
