# Generated by Django 5.2.9 on 2026-01-20 15:01

from django.db import migrations, models
from django.contrib.contenttypes.models import ContentType


def create_conceptual_nodes(apps, app_name, model_name, node_type):
    ConceptualNode = apps.get_model('canvases', 'ConceptualNode')

    ModelClass = apps.get_model(app_name, model_name)
    content_type = ContentType.objects.get_for_model(ModelClass)
    for instance in ModelClass.objects.all():
        if model_name == 'ReflectionLog':
            label = instance.title
        else:
            label = instance.label

        new_node = ConceptualNode(
            label=label,
            node_type=node_type,
            content_type_id=content_type.pk,
            object_id=instance.id
        )
        new_node.save()

def forward_func(apps, schema_editor):
    create_conceptual_nodes(apps, 'knowledge', 'TopicKeyword', 'CONCEPT')
    create_conceptual_nodes(apps, 'knowledge', 'TopicScopeElement', 'GROUP')
    create_conceptual_nodes(apps, 'workflows', 'ReflectionLog', 'INSIGHT')

def reverse_func(apps, schema_editor):
    # Optional: code to revert the changes if unapplied
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0002_rename_canvases_canvasnoderelation_canvas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptualnode',
            name='solidity',
            field=models.CharField(choices=[('SOLID', 'Solid'), ('PULSING', 'Pulsing'), ('DIMMED', 'Dimmed')], default='DIMMED', max_length=20),
        ),
        migrations.RunPython(forward_func, reverse_func),
    ]
