# Generated by Django 5.2.9 on 2026-03-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0002_remove_canvasnoderelation_anchor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptualedge',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
    ]
