# Generated by Django 5.2.9 on 2026-03-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0003_conceptualedge_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptualedge',
            name='source_handle',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conceptualedge',
            name='target_handle',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='canvasnoderelation',
            constraint=models.UniqueConstraint(fields=('node', 'canvas'), name='unique_conceptual_node_per_canvas'),
        ),
    ]
