# Generated by Django 6.0.5 on 2026-06-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0003_remove_conceptualedge_unique_conceptual_edge_per_canvas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptualedge',
            name='status',
            field=models.CharField(choices=[('USER_DRAFT', 'User Draft'), ('AI_EXTRACTED', 'AI Extracted'), ('LOCKED', 'Locked'), ('ON_HOLD', 'On Hold'), ('ARCHIVED', 'Archived')], default='AI_EXTRACTED', max_length=20),
        ),
    ]
