# Generated by Django 5.2.9 on 2026-01-21 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0003_alter_conceptualnode_solidity'),
        ('workflows', '0002_explorationphasedata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptualcanvas',
            name='workflow',
            field=models.ForeignKey(default='', help_text='The ID of the user owning this workflow.', on_delete=django.db.models.deletion.CASCADE, to='workflows.researchworkflow'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conceptualnode',
            name='groundedness',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='conceptualnode',
            name='solidity',
            field=models.CharField(choices=[('SOLID', 'Solid'), ('PULSING', 'Pulsing'), ('DIMMED', 'Dimmed')], default='PULSING', max_length=20),
        ),
    ]
