# Generated by Django 6.0.5 on 2026-06-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0004_conceptualedge_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptualnode',
            name='rationale',
            field=models.TextField(blank=True, default='', help_text="AI's justification or reasoning for this node.", null=True),
        ),
    ]
