# Generated by Django 5.2.6 on 2026-03-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0004_conceptualcanvas_workflow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasnoderelation',
            name='status',
            field=models.CharField(choices=[('USER_DRAFT', 'User Draft'), ('AI_EXTRACTED', 'AI Extracted'), ('LOCKED', 'Locked'), ('ON_HOLD', 'On Hold'), ('ARCHIVED', 'Archived')], default='AI_EXTRACTED', max_length=20),
        ),
    ]
