# Generated by Django 6.0.5 on 2026-07-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0005_alter_conceptualnode_rationale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptualnode',
            name='anchor',
        ),
        migrations.RemoveField(
            model_name='conceptualnode',
            name='groundedness',
        ),
        migrations.RemoveField(
            model_name='conceptualnode',
            name='solidity',
        ),
    ]
