# Generated by Django 6.0.5 on 2026-07-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0006_remove_conceptualnode_anchor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptualnode',
            name='status',
            field=models.CharField(choices=[('USER_DRAFT', 'User Draft'), ('AI_EXTRACTED', 'AI Extracted'), ('LOCKED', 'Locked'), ('ON_HOLD', 'On Hold'), ('ARCHIVED', 'Archived')], default='AI_EXTRACTED', max_length=20),
        ),
    ]
