# Generated by Django 6.0.5 on 2026-07-10 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvases', '0007_conceptualnode_status'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptualnode',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='conceptualnode',
            name='object_id',
            field=models.UUIDField(blank=True, help_text='The UUID of the specific owner instance.', null=True),
        ),
    ]
