# Generated by Django 5.2.6 on 2025-12-11 07:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchWorkflowState',
            fields=[
                ('session_id', models.UUIDField(editable=False, help_text='Unique identifier for the current research workflow session.', primary_key=True, serialize=False)),
                ('current_stage', models.CharField(choices=[('INITIATION', '1. Topic Definition & Lock-in (Uncertainty → Optimism)'), ('EXPLORATION', '2. Exploration (Confusion/Doubt)'), ('FORMULATION', '3. Formulation (Clarity)'), ('COLLECTION', '4. Collection (Satisfaction)'), ('PRESENTATION', '5. Presentation (Closure)')], default='INITIATION', help_text='Current Kuhlthau phase (INITIATION, SELECTION, etc.).', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the workflow is currently in progress or concluded.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The ID of the user owning this workflow.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Research Workflow State',
                'verbose_name_plural': 'Research Workflow States',
            },
        ),
        migrations.CreateModel(
            name='UserReflectionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the reflection entry.', primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('entry_text', models.TextField(help_text="The user's self-reported reflection text.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InitiationPhaseData',
            fields=[
                ('workflow_state', models.OneToOneField(help_text='One-to-one link to the parent ResearchWorkflowState (Control Model).', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='initiation_data', serialize=False, to='workflows.researchworkflowstate')),
                ('stability_score', models.IntegerField(default=0, help_text="The Agent's Stability Score [1-10]. Used to derive clarity label and progress visualization.")),
                ('feasibility_status', models.CharField(default='LOW', help_text='The Feasibility Status (e.g., LOW, MEDIUM, HIGH) derived from Agent input and structural rules.', max_length=10)),
                ('final_research_question', models.TextField(blank=True, default='', help_text='The most refined draft of the research question extracted by the Agent.')),
                ('conversation_summary', models.TextField(blank=True, default='', help_text='The cumulative, incremental summary of the conversation, maintained by the Summarizer Agent (Long-Term Memory).')),
                ('last_analysis_sequence_number', models.IntegerField(default=0, help_text='The sequence number of the last chat message included in the latest structured analysis (TR Agent) or summary (SUM Agent). Serves as the checkpoint anchor for the next incremental operation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latest_reflection_entry', models.ForeignKey(blank=True, help_text='The specific reflection log entry that was included in the last TR Agent structured analysis.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyzed_in_initiation', to='workflows.userreflectionlog')),
            ],
            options={
                'verbose_name': 'Initiation Phase Data',
                'verbose_name_plural': 'Initiation Phase Data',
            },
        ),
        migrations.CreateModel(
            name='ChatHistoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Unique identifier (UUID) for the chat message, corresponding to the frontend's ID.", primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('system', 'System/Agent')], help_text="The role of the sender ('user' or 'system').", max_length=10)),
                ('content', models.TextField(help_text='The text content of the chat message.')),
                ('name', models.CharField(blank=True, help_text="Specific sender identifier (e.g., username, 'Explorer Agent', 'Data Agent').", max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The exact time the message was recorded.')),
                ('sequence_number', models.IntegerField(help_text="The sequential order of the message within the workflow's history.")),
                ('workflow_state', models.ForeignKey(help_text='Foreign key linking the message to the parent research workflow session.', on_delete=django.db.models.deletion.CASCADE, related_name='chat_history_entries', to='workflows.researchworkflowstate')),
            ],
            options={
                'verbose_name': 'Chat History Entry',
                'verbose_name_plural': 'Chat History Entries',
                'ordering': ['timestamp', 'sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='TopicScopeElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the scope element entry.', primary_key=True, serialize=False)),
                ('label', models.CharField(help_text="The category of the scope element (e.g., 'Timeframe', 'Geographical Focus').", max_length=100)),
                ('value', models.CharField(help_text="The specific defined value (e.g., '2020-2023', 'Southeast Asia').", max_length=255)),
                ('status', models.CharField(choices=[('LOCKED', 'Locked (Committed and Finalized)'), ('USER_DRAFT', 'User Draft (Created by User, Pending Review)'), ('AI_EXTRACTED', 'AI Extracted (Captured by Agent, Needs Review)'), ('ON_HOLD', 'On Hold (Excluded from Current Topic)')], default='USER_DRAFT', help_text='The current status of the scope element (LOCKED, DRAFT, DISCARDED).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiation_data', models.ForeignKey(help_text='Link to the parent InitiationPhaseData record.', on_delete=django.db.models.deletion.CASCADE, related_name='scope_elements_list', to='workflows.initiationphasedata')),
            ],
            options={
                'verbose_name': 'Topic Scope Element',
                'verbose_name_plural': 'Topic Scope Elements',
                'indexes': [models.Index(fields=['initiation_data', 'label', 'status'], name='workflows_t_initiat_1fbafa_idx')],
            },
        ),
        migrations.CreateModel(
            name='TopicKeyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the keyword entry.', primary_key=True, serialize=False)),
                ('text', models.CharField(help_text='The keyword or key phrase itself.', max_length=255)),
                ('status', models.CharField(choices=[('LOCKED', 'Locked (Committed and Finalized)'), ('USER_DRAFT', 'User Draft (Created by User, Pending Review)'), ('AI_EXTRACTED', 'AI Extracted (Captured from Chat, Needs Review)'), ('ON_HOLD', 'On Hold (Excluded from Current Topic)')], default='USER_DRAFT', help_text='The current status of the keyword (LOCKED, DRAFT, DISCARDED).', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Agent-assigned confidence score for this keyword extraction.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiation_data', models.ForeignKey(help_text='Link to the parent InitiationPhaseData record.', on_delete=django.db.models.deletion.CASCADE, related_name='keywords_list', to='workflows.initiationphasedata')),
            ],
            options={
                'verbose_name': 'Topic Keyword',
                'verbose_name_plural': 'Topic Keywords',
                'indexes': [models.Index(fields=['initiation_data', 'status'], name='workflows_t_initiat_ea7d1a_idx')],
            },
        ),
    ]
