# Generated by Django 5.2.6 on 2025-11-13 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='workflow_state', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Associated User')),
                ('current_step', models.CharField(choices=[('SEARCH', '1. Search & Data Lock'), ('SCOPE', '2. Define Scope & Tension'), ('COLLECTION', '3. Opinion Collection'), ('ANALYSIS', '4. Analyze Conflicts'), ('OUTPUT', '5. Final Strategy Output')], default='SEARCH', help_text='The current active step in the workflow.', max_length=50)),
                ('scope_data', models.JSONField(default=dict, help_text='Stores dichotomy, roles, and focused question.')),
                ('analysis_data', models.JSONField(default=dict, help_text='Stores Agent opinions, conflict summaries, and final output data.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, help_text='The search query that initially retrieved this result.', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('snippet', models.TextField()),
                ('url', models.URLField(max_length=500)),
                ('source', models.CharField(blank=True, help_text="The source name (e.g., 'TechCrunch').", max_length=100, null=True)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('workflow_state', models.ForeignKey(help_text='The specific workflow session that has locked this source.', on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_sources', to='workflows.workflowstate')),
            ],
            options={
                'verbose_name_plural': 'Knowledge Sources',
                'indexes': [models.Index(fields=['workflow_state', 'url'], name='workflows_k_workflo_99b097_idx')],
            },
        ),
    ]
