# Generated by Django 5.2.6 on 2025-12-03 05:56

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchWorkflowState',
            fields=[
                ('session_id', models.UUIDField(editable=False, help_text='Unique identifier for the current research workflow session.', primary_key=True, serialize=False)),
                ('current_stage', models.CharField(choices=[('INITIATION', '1. Initiation (Uncertainty)'), ('SELECTION', '2. Selection (Optimism)'), ('EXPLORATION', '3. Exploration (Confusion/Doubt)'), ('FORMULATION', '4. Formulation (Clarity)'), ('COLLECTION', '5. Collection (Satisfaction)'), ('PRESENTATION', '6. Presentation (Closure)')], default='INITIATION', help_text='Current Kuhlthau phase (INITIATION, SELECTION, etc.).', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the workflow is currently in progress or concluded.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The ID of the user owning this workflow.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Research Workflow State',
                'verbose_name_plural': 'Research Workflow States',
            },
        ),
        migrations.CreateModel(
            name='InitiationPhaseData',
            fields=[
                ('workflow_state', models.OneToOneField(help_text='One-to-one link to the parent ResearchWorkflowState (Control Model).', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='initiation_data', serialize=False, to='workflows.researchworkflowstate')),
                ('clarity_score', models.FloatField(default=0.0, help_text='The current Clarity Score (S) [0.0 - 1.0]. Used for decision making (L-4.1).')),
                ('da_activation_threshold', models.FloatField(default=0.35, help_text="The Clarity Score threshold (tau_DA) required to trigger the Data Agent's asynchronous work.")),
                ('optimized_keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text="Keywords (K') validated and optimized by the Data Agent (DA). Output of this phase.", size=None)),
                ('last_da_execution_time', models.DateTimeField(blank=True, help_text='Timestamp of the last completed Data Agent background validation run.', null=True)),
                ('keyword_stability_count', models.IntegerField(default=0, help_text='Consecutive turns where preliminary keywords showed no significant change. Used for DA activation control.')),
                ('is_transition_ready', models.BooleanField(default=False, help_text="True if S > tau_EA AND K' has been updated. Used to enable the UI button.")),
                ('chat_history', models.JSONField(default=list, help_text='Stores the sequential conversation history for context passing.')),
                ('unverified_keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Keywords (K_pre) extracted by EA but not yet validated by DA.', size=None)),
                ('da_validation_report', models.JSONField(default=dict, help_text='Detailed JSON report from the Data Agent (DA) after validation (includes IDF/QMS).')),
                ('ea_reasoning_log', models.JSONField(default=dict, help_text='Detailed reasoning log from the Explorer Agent (EA) for S calculation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Initiation Phase Data',
                'verbose_name_plural': 'Initiation Phase Data',
            },
        ),
    ]
