# Generated by Django 5.2.6 on 2025-12-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='topickeyword',
            constraint=models.UniqueConstraint(fields=('initiation_data', 'text'), name='unique_keyword_per_session'),
        ),
        migrations.AddConstraint(
            model_name='topicscopeelement',
            constraint=models.UniqueConstraint(fields=('initiation_data', 'label', 'value'), name='unique_scope_element_per_session'),
        ),
    ]
