# Generated by Django 5.2.6 on 2025-11-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstate',
            name='query',
            field=models.CharField(db_index=True, default='', help_text='The search query that initially retrieved this result.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workflowstate',
            name='scope_data',
            field=models.JSONField(default=None, help_text='Stores dichotomy, roles, and focused question.'),
        ),
    ]
