# Generated by Django 5.2.6 on 2025-12-04 06:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiationphasedata',
            name='chat_history',
        ),
        migrations.CreateModel(
            name='ChatHistoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Unique identifier (UUID) for the chat message, corresponding to the frontend's ID.", primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('system', 'System/Agent')], help_text="The role of the sender ('user' or 'system').", max_length=10)),
                ('content', models.TextField(help_text='The text content of the chat message.')),
                ('name', models.CharField(blank=True, help_text="Specific sender identifier (e.g., username, 'Explorer Agent', 'Data Agent').", max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The exact time the message was recorded.')),
                ('sequence_number', models.IntegerField(help_text="The sequential order of the message within the workflow's history.")),
                ('workflow_state', models.ForeignKey(help_text='Foreign key linking the message to the parent research workflow session.', on_delete=django.db.models.deletion.CASCADE, related_name='chat_history_entries', to='workflows.researchworkflowstate')),
            ],
            options={
                'verbose_name': 'Chat History Entry',
                'verbose_name_plural': 'Chat History Entries',
                'ordering': ['timestamp', 'sequence_number'],
            },
        ),
    ]
