# Generated by Django 5.2.9 on 2026-01-20 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplorationPhaseData',
            fields=[
                ('workflow', models.OneToOneField(help_text='One-to-one link to the parent ResearchWorkflow (Control Model).', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='exploration_data', serialize=False, to='workflows.researchworkflow')),
                ('stability_score', models.IntegerField(default=0, help_text="The Agent's Stability Score [1-10]. Used to derive clarity label and progress visualization.")),
                ('final_research_question', models.TextField(blank=True, default='', help_text='The most refined draft of the research question extracted by the Agent.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exploration Phase Data',
                'verbose_name_plural': 'Exploration Phase Data',
            },
        ),
        migrations.AlterField(
            model_name='researchworkflow',
            name='current_stage',
            field=models.CharField(choices=[('DEFINITION', 'Definition'), ('EXPLORATION', 'Exploration'), ('FORMULATION', 'Formulation'), ('COLLECTION', 'Collection'), ('PRESENTATION', 'Presentation')], default='DEFINITION', help_text='Current ISP phase (DEFINITION, EXPLORATION, etc.).', max_length=50),
        ),
    ]
