# Generated by Django 5.2.6 on 2025-12-13 14:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


def copy_data_to_foreign_key(apps, schema_editor):
    TopicKeyword = apps.get_model('workflows', 'TopicKeyword')
    TopicScopeElement = apps.get_model('workflows', 'TopicScopeElement')
    ResearchWorkflowState = apps.get_model('workflows', 'ResearchWorkflowState')

    for instance in TopicKeyword.objects.all():
        try:
            # Logic to find the related object based on the old data
            related_instance = ResearchWorkflowState.objects.get(session_id=instance.initiation_data_id)
            instance.workflow_state = related_instance
            instance.save()
        except ResearchWorkflowState.DoesNotExist:
            # Handle cases where the related object might not exist
            continue

    for instance in TopicScopeElement.objects.all():
        try:
            # Logic to find the related object based on the old data
            related_instance = ResearchWorkflowState.objects.get(session_id=instance.initiation_data_id)
            instance.workflow_state = related_instance
            instance.save()
        except ResearchWorkflowState.DoesNotExist:
            # Handle cases where the related object might not exist
            continue

def reverse_data_transfer(apps, schema_editor):
    # Optional: logic to reverse the data transfer if needed
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_topickeyword_unique_keyword_per_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReflectionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the reflection entry.', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='A short summary title for the log entry.', max_length=255)),
                ('content', models.TextField(help_text='The detailed reflection content or thought.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMMITTED', 'Committed')], default='DRAFT', help_text='The current state of the log (DRAFT or COMMITTED).', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The exact time the log entry was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='The time the log entry was last modified/saved.')),
            ],
            options={
                'verbose_name': 'Reflection Log Entry',
                'verbose_name_plural': 'Reflection Log Entries',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RemoveField(
            model_name='initiationphasedata',
            name='latest_reflection_entry',
        ),
        migrations.AlterModelOptions(
            name='topickeyword',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Topic Keyword', 'verbose_name_plural': 'Topic Keywords'},
        ),
        migrations.AlterModelOptions(
            name='topicscopeelement',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Topic Scope Element', 'verbose_name_plural': 'Topic Scope Elements'},
        ),
        migrations.RemoveConstraint(
            model_name='topickeyword',
            name='unique_keyword_per_session',
        ),
        migrations.RemoveConstraint(
            model_name='topicscopeelement',
            name='unique_scope_element_per_session',
        ),
        migrations.RemoveIndex(
            model_name='topickeyword',
            name='workflows_t_initiat_ea7d1a_idx',
        ),
        migrations.RemoveIndex(
            model_name='topicscopeelement',
            name='workflows_t_initiat_1fbafa_idx',
        ),
        migrations.AddField(
            model_name='topickeyword',
            name='workflow_state',
            field=models.ForeignKey(default=None, null=True, blank=True, help_text='Foreign key linking the keyword to the parent research workflow session.', on_delete=django.db.models.deletion.CASCADE, related_name='keywords_list', to='workflows.researchworkflowstate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topicscopeelement',
            name='workflow_state',
            field=models.ForeignKey(default=None, null=True, blank=True, help_text='Foreign key linking the scope element to the parent research workflow session.', on_delete=django.db.models.deletion.CASCADE, related_name='scope_elements_list', to='workflows.researchworkflowstate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topickeyword',
            name='initiation_data',
            field=models.ForeignKey(help_text='Foreign key linking the keyword to the parent initial phase data session.', on_delete=django.db.models.deletion.CASCADE, related_name='keywords_list', to='workflows.initiationphasedata'),
        ),
        migrations.AlterField(
            model_name='topicscopeelement',
            name='initiation_data',
            field=models.ForeignKey(help_text='Foreign key linking the scope to the parent initial phase data session.', on_delete=django.db.models.deletion.CASCADE, related_name='scope_elements_list', to='workflows.initiationphasedata'),
        ),
        migrations.AddIndex(
            model_name='topickeyword',
            index=models.Index(fields=['workflow_state', 'status'], name='workflows_t_workflo_5e3765_idx'),
        ),
        migrations.AddIndex(
            model_name='topicscopeelement',
            index=models.Index(fields=['workflow_state', 'label', 'status'], name='workflows_t_workflo_6acace_idx'),
        ),
        migrations.AddConstraint(
            model_name='topickeyword',
            constraint=models.UniqueConstraint(fields=('workflow_state', 'text'), name='unique_keyword_per_session'),
        ),
        migrations.AddConstraint(
            model_name='topicscopeelement',
            constraint=models.UniqueConstraint(fields=('workflow_state', 'label', 'value'), name='unique_scope_element_per_session'),
        ),
        migrations.AddField(
            model_name='reflectionlog',
            name='workflow_state',
            field=models.ForeignKey(help_text='Foreign key linking the reflection logs to the parent research workflow session.', on_delete=django.db.models.deletion.CASCADE, related_name='reflection_log_entries', to='workflows.researchworkflowstate'),
        ),
        migrations.DeleteModel(
            name='UserReflectionLog',
        ),
        migrations.RunPython(copy_data_to_foreign_key, reverse_data_transfer),
    ]
