# Generated by Django 5.2.9 on 2026-03-09 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_explorationphasedata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchworkflow',
            old_name='session_id',
            new_name='workflow_id',
        ),
    ]
