# Generated by Django 5.2.6 on 2025-11-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_workflowstate_query_alter_workflowstate_scope_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstate',
            name='analysis_data',
            field=models.JSONField(default=None, help_text='Stores Agent opinions, conflict summaries, and final output data.'),
        ),
    ]
