# Generated by Django 5.2.6 on 2025-12-05 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_remove_initiationphasedata_chat_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiationphasedata',
            name='clarity_score',
        ),
        migrations.RemoveField(
            model_name='initiationphasedata',
            name='da_activation_threshold',
        ),
        migrations.RemoveField(
            model_name='initiationphasedata',
            name='da_validation_report',
        ),
        migrations.RemoveField(
            model_name='initiationphasedata',
            name='ea_reasoning_log',
        ),
        migrations.RemoveField(
            model_name='initiationphasedata',
            name='is_transition_ready',
        ),
        migrations.RemoveField(
            model_name='initiationphasedata',
            name='keyword_stability_count',
        ),
        migrations.RemoveField(
            model_name='initiationphasedata',
            name='last_da_execution_time',
        ),
        migrations.RemoveField(
            model_name='initiationphasedata',
            name='optimized_keywords',
        ),
        migrations.RemoveField(
            model_name='initiationphasedata',
            name='unverified_keywords',
        ),
        migrations.AddField(
            model_name='initiationphasedata',
            name='conversation_summary',
            field=models.TextField(blank=True, default='', help_text='The cumulative, incremental summary of the conversation, maintained by the Summarizer Agent (Long-Term Memory).'),
        ),
        migrations.AddField(
            model_name='initiationphasedata',
            name='feasibility_status',
            field=models.CharField(default='LOW', help_text='The Feasibility Status (e.g., LOW, MEDIUM, HIGH) derived from Agent input and structural rules.', max_length=10),
        ),
        migrations.AddField(
            model_name='initiationphasedata',
            name='final_research_question',
            field=models.TextField(blank=True, default='', help_text='The most refined draft of the research question extracted by the Agent.'),
        ),
        migrations.AddField(
            model_name='initiationphasedata',
            name='last_analysis_sequence_number',
            field=models.IntegerField(default=0, help_text='The sequence number of the last chat message included in the latest structured analysis (TR Agent) or summary (SUM Agent). Serves as the checkpoint anchor for the next incremental operation.'),
        ),
        migrations.AddField(
            model_name='initiationphasedata',
            name='stability_score',
            field=models.IntegerField(default=0, help_text="The Agent's Stability Score [1-10]. Used to derive clarity label and progress visualization."),
        ),
        migrations.CreateModel(
            name='TopicKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='The keyword or key phrase itself.', max_length=255)),
                ('status', models.CharField(choices=[('LOCKED', 'Locked'), ('DRAFT', 'Draft'), ('DISCARDED', 'Discarded')], default='DRAFT', help_text='The current status of the keyword (LOCKED, DRAFT, DISCARDED).', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Agent-assigned confidence score for this keyword extraction.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiation_data', models.ForeignKey(help_text='Link to the parent InitiationPhaseData record.', on_delete=django.db.models.deletion.CASCADE, related_name='keywords_list', to='workflows.initiationphasedata')),
            ],
            options={
                'verbose_name': 'Topic Keyword',
                'verbose_name_plural': 'Topic Keywords',
                'indexes': [models.Index(fields=['initiation_data', 'status'], name='workflows_t_initiat_ea7d1a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TopicScopeElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="The category of the scope element (e.g., 'Timeframe', 'Geographical Focus').", max_length=100)),
                ('value', models.CharField(help_text="The specific defined value (e.g., '2020-2023', 'Southeast Asia').", max_length=255)),
                ('status', models.CharField(choices=[('LOCKED', 'Locked'), ('DRAFT', 'Draft'), ('DISCARDED', 'Discarded')], default='DRAFT', help_text='The current status of the scope element (LOCKED, DRAFT, DISCARDED).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiation_data', models.ForeignKey(help_text='Link to the parent InitiationPhaseData record.', on_delete=django.db.models.deletion.CASCADE, related_name='scope_elements_list', to='workflows.initiationphasedata')),
            ],
            options={
                'verbose_name': 'Topic Scope Element',
                'verbose_name_plural': 'Topic Scope Elements',
                'indexes': [models.Index(fields=['initiation_data', 'label', 'status'], name='workflows_t_initiat_1fbafa_idx')],
            },
        ),
    ]
