# Generated by Django 5.2.6 on 2025-12-05 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_remove_initiationphasedata_clarity_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReflectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('entry_text', models.TextField(help_text="The user's self-reported reflection text.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='initiationphasedata',
            name='latest_reflection_entry',
            field=models.ForeignKey(blank=True, help_text='The specific reflection log entry that was included in the last TR Agent structured analysis.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyzed_in_initiation', to='workflows.userreflectionlog'),
        ),
    ]
