# Generated by Django 5.2.6 on 2025-11-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_alter_workflowstate_analysis_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstate',
            name='suggested_dichotomies_cache',
            field=models.JSONField(blank=True, default=None, help_text='Transient cache for AI-generated dichotomy suggestions (JSON format).', null=True),
        ),
    ]
