# Generated by Django 5.2.6 on 2025-12-13 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_reflectionlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topickeyword',
            name='workflow_state',
            field=models.ForeignKey(help_text='Foreign key linking the keyword to the parent research workflow session.', on_delete=django.db.models.deletion.CASCADE, related_name='keywords_list', to='workflows.researchworkflowstate'),
        ),
        migrations.AlterField(
            model_name='topicscopeelement',
            name='workflow_state',
            field=models.ForeignKey(help_text='Foreign key linking the scope element to the parent research workflow session.', on_delete=django.db.models.deletion.CASCADE, related_name='scope_elements_list', to='workflows.researchworkflowstate'),
        ),
    ]
