# Generated by Django 5.2.9 on 2026-03-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_rename_session_id_researchworkflow_workflow_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='explorationphasedata',
            name='activated_canvas_id',
            field=models.UUIDField(null=True),
        ),
    ]
