# Generated by Django 5.2.9 on 2026-03-10 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_explorationphasedata_activated_canvas_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='explorationphasedata',
            old_name='activated_canvas_id',
            new_name='active_canvas_id',
        ),
    ]
