# Generated by Django 5.2.6 on 2025-12-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_userreflectionlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchworkflowstate',
            name='current_stage',
            field=models.CharField(choices=[('INITIATION', '1. Topic Definition & Lock-in (Uncertainty → Optimism)'), ('EXPLORATION', '2. Exploration (Confusion/Doubt)'), ('FORMULATION', '3. Formulation (Clarity)'), ('COLLECTION', '4. Collection (Satisfaction)'), ('PRESENTATION', '5. Presentation (Closure)')], default='INITIATION', help_text='Current Kuhlthau phase (INITIATION, SELECTION, etc.).', max_length=50),
        ),
    ]
