# Generated by Django 5.2.9 on 2025-12-17 07:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicKeyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when this record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when this record was last modified.')),
                ('label', models.CharField(help_text='The text content of the keyword.', max_length=255)),
                ('object_id', models.UUIDField(help_text='The UUID of the specific owner instance.')),
                ('importance_weight', models.FloatField(default=0.5, help_text='Weighted significance from 0.0 to 1.0.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_core', models.BooleanField(default=False, help_text='Identifies if this is a central concept of the research.')),
                ('semantic_category', models.CharField(blank=True, help_text="e.g., 'Methodology', 'Theory', 'Technology'.", max_length=100, null=True)),
                ('status', models.CharField(choices=[('USER_DRAFT', 'User Draft'), ('AI_EXTRACTED', 'AI Extracted'), ('LOCKED', 'Locked'), ('ON_HOLD', 'On Hold'), ('ARCHIVED', 'Archived')], default='AI_EXTRACTED', max_length=20)),
                ('content_type', models.ForeignKey(help_text='The model type of the owner (Workflows, Resources, etc.)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Topic Keyword',
                'verbose_name_plural': 'Topic Keywords',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when this record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when this record was last modified.')),
                ('label', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('format', models.CharField(choices=[('URL', 'Web URL'), ('PDF', 'PDF Document'), ('DOCUMENT', 'Local Document'), ('IMAGE', 'Visual Data'), ('SNIPPET', 'Text Snippet')], default='URL', max_length=20)),
                ('source_type', models.CharField(choices=[('ACADEMIC', 'Academic Source'), ('NEWS', 'News/Media'), ('SOCIAL', 'Social Discourse'), ('GOVERNMENT', 'Official/Policy'), ('MANUAL', 'Manual Input'), ('AI_GENERATED', 'AI Synthesized')], default='MANUAL', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('raw_content', models.TextField(blank=True, help_text='Stored content for AI analysis or indexing.', null=True)),
                ('related_keywords', models.ManyToManyField(blank=True, related_name='resources', to='knowledge.topickeyword')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopicScopeElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when this record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when this record was last modified.')),
                ('label', models.CharField(help_text="The aspect of the scope (e.g., 'Timeframe', 'Geography').", max_length=255)),
                ('object_id', models.UUIDField(help_text='The UUID of the specific owner instance.')),
                ('boundary_type', models.CharField(choices=[('INCLUSION', 'Inclusion'), ('EXCLUSION', 'Exclusion')], default='INCLUSION', max_length=20)),
                ('rationale', models.TextField(help_text="The reasoning behind this boundary (originally 'value').")),
                ('status', models.CharField(choices=[('USER_DRAFT', 'User Draft'), ('AI_EXTRACTED', 'AI Extracted'), ('LOCKED', 'Locked'), ('ON_HOLD', 'On Hold'), ('ARCHIVED', 'Archived')], default='AI_EXTRACTED', max_length=20)),
                ('content_type', models.ForeignKey(help_text='The model type of the owner (Workflows, Resources, etc.)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Topic Scope Element',
                'verbose_name_plural': 'Topic Scope Elements',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='topickeyword',
            index=models.Index(fields=['content_type', 'object_id'], name='knowledge_t_content_4cbec1_idx'),
        ),
        migrations.AddConstraint(
            model_name='topickeyword',
            constraint=models.UniqueConstraint(fields=('object_id', 'label'), name='unique_keyword_per_session'),
        ),
        migrations.AddIndex(
            model_name='topicscopeelement',
            index=models.Index(fields=['content_type', 'object_id'], name='knowledge_t_content_8ad6e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='topicscopeelement',
            constraint=models.UniqueConstraint(fields=('object_id', 'label', 'rationale'), name='unique_scope_element_per_session'),
        ),
    ]
