import logging
from types import SimpleNamespace
from typing import Any, Dict, List
from uuid import UUID

from canvases.models import (CanvasNodeRelation, ConceptualCanvas,
                             ConceptualEdge, ConceptualNode)
from canvases.serializers import (ConceptualEdgeSerializer,
                                  ConceptualGraphSerializer,
                                  ConceptualNodeSerializer)
from core.constants import EntityStatus
from core.utils import create_serialized_data
from django.apps import apps
from django.db import transaction
from django.db.models import Q
from django.shortcuts import get_object_or_404
from messaging.constants import (RecommendConceptualEdges,
                                 RecommendConceptualNodes)
from messaging.tasks import publish_event

logger = logging.getLogger(__name__)


def create_new_canvas_by_project_id(project_id: UUID):
    ResearchProject = apps.get_model('projects', 'ResearchProject')
    ExplorationPhaseData = apps.get_model('projects', 'ExplorationPhaseData')
    try:
        project = ResearchProject.objects.get(id=project_id)
    except ResearchProject.DoesNotExist:
        logger.error("Project with id %s does not exist. Cannot create canvas.", project_id)
        return

    canvas = ConceptualCanvas.objects.filter(project=project)

    if canvas.exists():
        logger.warning("Project %s already has a canvas. Skipping creation.", project_id)
        return

    canvas = ConceptualCanvas(name='Default Canvas', project=project)
    canvas.save()

    exploration_phase_data = ExplorationPhaseData.objects.get(project=project)
    setattr(exploration_phase_data, 'active_canvas_id', canvas.id)
    exploration_phase_data.save()

    node = ConceptualNode(label=canvas.name, node_type='NAVIGATION')
    canvas.navigator.add(node, bulk=False)

    return canvas

def create_conceptual_edge(canvas_id: str, data, serializer_class):
    canvas = get_object_or_404(ConceptualCanvas, id=canvas_id)
    return create_serialized_data(data, serializer_class, canvas=canvas)

def create_or_update_conceptual_edges(canvas_id: str, data: list):
    """
    Synchronizes edge data for a specific canvas.
    Handles bulk creation of new edges and bulk updates for existing ones.
    """
    # 1. Fetch all existing edges for this canvas to determine what to update vs create
    existing_edges = ConceptualEdge.objects.filter(canvas_id=canvas_id).select_related('source', 'target')

    # Map existing edges by ID for O(1) lookup
    # We use the edge ID (UUID) as the primary key for synchronization
    edge_map = {}
    for edge in existing_edges:
        edge_key = f"{str(edge.source.id)}_{edge.edge_type}_{str(edge.target.id)}"
        edge_map[edge_key] = edge

    to_create = []
    to_update = []

    for edge_data in data:
        source = edge_data.get('source')
        target = edge_data.get('target')
        edge_type = edge_data.get('type')
        edge_key = f"{source}_{edge_type}_{target}"

        if edge_key in edge_map:
            # --- Update Logic ---
            instance = edge_map[edge_key]
            instance.label = edge_data.get('label', instance.label)
            instance.edge_type = edge_data.get('type', instance.edge_type)
            instance.evidence = edge_data.get('evidence', instance.evidence)
            instance.weight = edge_data.get('weight', instance.weight)
            instance.rationale = edge_data.get('rationale', instance.rationale)
            instance.metadata = edge_data.get('metadata', instance.metadata)
            instance.source_handle = edge_data.get('sourceHandle', instance.source_handle)
            instance.target_handle = edge_data.get('targetHandle', instance.target_handle)
            to_update.append(instance)
        else:
            # --- Create Logic ---
            # Ensure we only create if the edge doesn't exist (ID-based)
            to_create.append(ConceptualEdge(
                id=edge_data['id'], # Preserve the UUID generated by the frontend
                source_id=edge_data['source'],
                target_id=edge_data['target'],
                source_handle=edge_data.get('sourceHandle'),
                target_handle=edge_data.get('targetHandle'),
                label=edge_data.get('label', ''),
                edge_type=edge_data.get('type', 'REF'),
                evidence=edge_data.get('evidence', ''),
                weight=edge_data.get('weight', 1.0),
                rationale=edge_data.get('rationale', ''),
                metadata=edge_data.get('metadata', {}),
                canvas_id=canvas_id
            ))

    # 2. Execute database operations within a transaction for atomicity
    with transaction.atomic():
        if to_create:
            ConceptualEdge.objects.bulk_create(to_create)

        if to_update:
            ConceptualEdge.objects.bulk_update(
                to_update,
                fields=[
                    'label', 'edge_type', 'evidence', 'weight',
                    'rationale', 'metadata', 'source_handle', 'target_handle'
                ]
            )

    return {"created": len(to_create), "updated": len(to_update)}

def create_or_update_conceptual_node_relations(canvas_id: str, data: Dict[str, Any]):
    relation_instances = CanvasNodeRelation.objects.filter(canvas__id=canvas_id).all()
    on_canvas_nodes = {str(relation.node.id): relation for relation in relation_instances}

    instances = []
    for node_id, node in data.items():
        if node_id in on_canvas_nodes:
            relation = on_canvas_nodes[node_id]
            relation.x = node['position'].get('x')
            relation.y = node['position'].get('y')
        else:
            relation = CanvasNodeRelation(
                canvas_id=canvas_id,
                node_id=node_id,
                x=node['position'].get('x'),
                y=node['position'].get('y'),
                rationale=node.get('rationale'),
                status=EntityStatus.AI_EXTRACTED
            )

        instances.append(relation)

    CanvasNodeRelation.objects.bulk_create(instances, ignore_conflicts=True)

def get_conceptual_graph(canvas_id: str):
    canvas_node_relations = CanvasNodeRelation.objects.filter(canvas__id=canvas_id).all()
    on_canvas_edges = ConceptualEdge.objects.filter(canvas__id=canvas_id).all()
    on_graph_nodes = {}
    for relation in canvas_node_relations:
        node = set_position_to_relation_nodes(relation)
        on_graph_nodes[node.id] = node

    graph_instance = SimpleNamespace(
        canvas_id=canvas_id,
        nodes={relation.node.id: relation.node for relation in canvas_node_relations},
        edges=on_canvas_edges
    )
    conceptual_graph_serializer = ConceptualGraphSerializer(graph_instance)
    return conceptual_graph_serializer.data

def get_conceptual_edges(canvas_id: str):
    on_canvas_edges = ConceptualEdge.objects.filter(canvas__id=canvas_id).all()
    conceptual_edges_serializer = ConceptualEdgeSerializer(on_canvas_edges)
    return conceptual_edges_serializer.data

def get_conceptual_edges_recommendation(
        user_id: UUID,
        canvas_id: UUID,
        newly_onboarded_nodes: List[ConceptualNode]
    ):

    canvas_node_relations = CanvasNodeRelation.objects.filter(canvas__id=canvas_id).exclude(node__status='ON_HOLD').all()
    on_canvas_str = "\n".join([f"- [{relation.node.node_type}] {relation.node.label} (ID: {relation.node.id})" for relation in canvas_node_relations])
    on_canvas_ids = [str(relation.node.id) for relation in canvas_node_relations]

    payload = {
        'user_id': user_id,
        'canvas_id': canvas_id,
        'on_canvas_str': on_canvas_str,
        'on_canvas_ids': on_canvas_ids,
        'newly_onboarded_nodes': newly_onboarded_nodes,
        'recommendation_mode': 'autonomous',
    }

    publish_event.delay(
        event_type=RecommendConceptualEdges.name,
        payload=payload,
        queue=RecommendConceptualEdges.queue
    )

def get_conceptual_nodes_recommendation(user_id: UUID, project_id: UUID, canvas_id: UUID):
    """
    """
    publish_event.delay(
        event_type=RecommendConceptualNodes.name,
        payload={
            'user_id': user_id,
            'canvas_id': canvas_id,
            'project_id': project_id
        },
        queue=RecommendConceptualNodes.queue
    )

def delete_canvas_node_relation_by_constraint(canvas_id: str, node_id: str):
    instance = CanvasNodeRelation.objects.get(canvas_id=canvas_id, node_id=node_id)
    if not instance:
        return

    with transaction.atomic():
        ConceptualEdge.objects.filter(
            Q (canvas_id=canvas_id) & (Q(source=node_id) | Q(target=node_id))
        ).delete()
        instance.delete()

def set_position_to_relation_nodes(relation: CanvasNodeRelation):
    position = SimpleNamespace(
        x=relation.x,
        y=relation.y
    )
    setattr(relation.node, 'position', position)
    setattr(relation.node, 'status', relation.status)
    return relation.node

def update_canvas_node_relation_by_constraint(canvas_id: str, node_id: str, data: Dict[str, Any]):
    instance = CanvasNodeRelation.objects.get(canvas_id=canvas_id, node_id=node_id)
    for key, value in data.items():
        if value is None or key in ['id']:
            continue

        if key == 'position':
            instance.x = value['x']
            instance.y = value['y']

        setattr(instance, key, value)

    instance.save()

    node = set_position_to_relation_nodes(instance)
    serializer = ConceptualNodeSerializer(node)
    return serializer.data
