# Generated by Django 5.2.6 on 2025-11-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRoleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The unique name used to identify this agent role (e.g., 'Dichotomy Suggester').", max_length=100, unique=True)),
                ('system_prompt', models.TextField(help_text='The instruction set given to the LLM to define its persona and task.')),
                ('output_schema', models.JSONField(help_text='The JSON schema defining the required output structure for the LLM response.')),
                ('llm_parameters', models.JSONField(blank=True, default=dict, help_text='Specific runtime parameters for the LLM call (e.g., temperature, top_p, max_tokens).')),
            ],
            options={
                'verbose_name': 'Agent Role Configuration',
                'verbose_name_plural': 'Agent Role Configurations',
            },
        ),
    ]
