# Generated by Django 5.2.6 on 2025-12-11 07:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRoleConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the agent role configuration.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="The unique name used to identify this agent role (e.g., 'Dichotomy Suggester').", max_length=100, unique=True)),
                ('system_prompt', models.TextField(help_text='The instruction set given to the LLM to define its persona and task.')),
                ('prompt_template', models.TextField(blank=True, help_text='The full template text used to render the final prompt, containing all static text and {{variable}} placeholders.', null=True)),
                ('template_variables', models.JSONField(blank=True, default=dict, help_text="A dictionary defining the dynamic variables required by the prompt_template and their data source/type (e.g., {'final_question_draft': 'DB_FACTS', 'latest_user_input': 'CURRENT_TURN'}).")),
                ('output_schema', models.JSONField(help_text='The JSON schema defining the required output structure for the LLM response.')),
                ('llm_parameters', models.JSONField(blank=True, default=dict, help_text='Specific runtime parameters for the LLM call (e.g., temperature, top_p, max_tokens).')),
            ],
            options={
                'verbose_name': 'Agent Role Configuration',
                'verbose_name_plural': 'Agent Role Configurations',
            },
        ),
    ]
