# Generated by Django 5.2.11 on 2026-03-31 12:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('projects', '0003_remove_researchproject_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentroleconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The timestamp when this record was first created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agentroleconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The timestamp when this record was last modified.'),
        ),
        migrations.AddField(
            model_name='agentroleconfig',
            name='user',
            field=models.ForeignKey(default='', null=True, help_text='The ID of the user owning this project.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agentroleconfig',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this entity.', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='AgentProjectRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when this record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when this record was last modified.')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agentroleconfig')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.researchproject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='agentroleconfig',
            name='projects',
            field=models.ManyToManyField(related_name='agent', through='agents.AgentProjectRelation', to='projects.researchproject'),
        ),
    ]
