# Generated by Django 5.2.6 on 2025-12-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentroleconfig',
            name='prompt_template',
            field=models.TextField(blank=True, help_text='The full template text used to render the final prompt, containing all static text and {{variable}} placeholders.', null=True),
        ),
        migrations.AddField(
            model_name='agentroleconfig',
            name='template_variables',
            field=models.JSONField(blank=True, default=dict, help_text="A dictionary defining the dynamic variables required by the prompt_template and their data source/type (e.g., {'final_question_draft': 'DB_FACTS', 'latest_user_input': 'CURRENT_TURN'})."),
        ),
    ]
