# Generated by Django 5.2.11 on 2026-04-08 06:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_alter_agentroleconfig_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this entity.', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(choices=[('GOOGLE', 'Google Gemini'), ('OPENAI', 'OpenAI'), ('ANTHROPIC', 'Anthropic'), ('LOCAL', 'Local / Custom (Ollama/vLLM)')], default='GOOGLE', max_length=20)),
                ('_encrypted_api_key', models.TextField(blank=True, db_column='api_key', null=True)),
                ('base_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('ACTIVE', 'Active'), ('ERROR', 'Error'), ('UNVERIFIED', 'Unverified')], default='UNVERIFIED', max_length=20)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The ID of the user owning this provider.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
