# Generated by Django 5.2.11 on 2026-04-08 07:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_modelprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFamilies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when this record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when this record was last modified.')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('input_token_limit', models.PositiveIntegerField()),
                ('output_token_limit', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='modelprovider',
            name='active_agent',
            field=models.ManyToManyField(blank=True, to='agents.agentroleconfig'),
        ),
        migrations.AddField(
            model_name='modelprovider',
            name='latency_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelprovider',
            name='supported_families',
            field=models.ManyToManyField(blank=True, to='agents.modelfamilies'),
        ),
    ]
