# Generated by Django 5.2.11 on 2026-04-20 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_modelfamilies_modelprovider_active_agent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentroleconfig',
            old_name='name',
            new_name='role',
        ),
    ]
