# Generated by Django 5.2.11 on 2026-04-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_modelfamilies_modelprovider_active_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentroleconfig',
            name='role',
            field=models.CharField(default='', help_text="The unique name used to identify this agent role (e.g., 'Dichotomy Suggester').", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agentroleconfig',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
