# Generated by Django 5.2.11 on 2026-04-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_rename_name_agentroleconfig_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentroleconfig',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
