# Generated by Django 6.0.5 on 2026-05-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_agentroleconfig_role_alter_agentroleconfig_name'),
        ('agents', '0007_agentroleconfig_name'),
    ]

    operations = [
    ]
