# Generated by Django 6.0.5 on 2026-06-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_agentroleconfig_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentroleconfig',
            name='output_schema',
            field=models.JSONField(blank=True, default=dict, help_text='The JSON schema defining the required output structure for the LLM response.'),
        ),
        migrations.AlterField(
            model_name='agentroleconfig',
            name='prompt_template',
            field=models.TextField(default='', help_text='The full template text used to render the final prompt, containing all static text and {{variable}} placeholders.'),
            preserve_default=False,
        ),
    ]
