# Generated by Django 5.2.11 on 2026-03-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='current_stage',
            field=models.CharField(choices=[('INITIATION', 'Initiation'), ('EXPLORATION', 'Exploration'), ('SYNTHESIS', 'Synthesis')], default='INITIATION', help_text='Current ISP phase (DEFINITION, EXPLORATION, etc.).', max_length=50),
        ),
    ]
