# Generated by Django 5.2.11 on 2026-03-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_researchproject_description_researchproject_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchproject',
            name='is_active',
        ),
        migrations.AddField(
            model_name='researchproject',
            name='status',
            field=models.CharField(choices=[('USER_DRAFT', 'User Draft'), ('AI_EXTRACTED', 'AI Extracted'), ('LOCKED', 'Locked'), ('ON_HOLD', 'On Hold'), ('ARCHIVED', 'Archived')], default='AI_EXTRACTED', max_length=20),
        ),
    ]
