# Generated by Django 5.2.11 on 2026-03-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentroleconfig_created_at_and_more'),
        ('projects', '0003_remove_researchproject_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='agents',
            field=models.ManyToManyField(related_name='project', through='agents.AgentProjectRelation', to='agents.agentroleconfig'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The timestamp when this record was first created.'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The timestamp when this record was last modified.'),
        ),
    ]
