# Generated by Django 6.0.5 on 2026-07-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_researchproject_agents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationphasedata',
            name='feasibility_status',
        ),
        migrations.RemoveField(
            model_name='consultationphasedata',
            name='final_research_question',
        ),
        migrations.RemoveField(
            model_name='consultationphasedata',
            name='stability_score',
        ),
        migrations.RemoveField(
            model_name='explorationphasedata',
            name='final_research_question',
        ),
        migrations.RemoveField(
            model_name='explorationphasedata',
            name='stability_score',
        ),
        migrations.DeleteModel(
            name='ReflectionLog',
        ),
    ]
