import uuid

from core.constants import EntityStatus, ISPStage
from core.models import BaseModel
from django.contrib.auth import get_user_model
from django.db import models

# Use the default Django User model for association
User = get_user_model()


class ResearchProject(BaseModel):
    """
    Core State Data Structure for managing a user's research project,
    tracking Kuhlthau phases, agent outputs, and cost control variables.
    """

    name = models.CharField(
        max_length=100,
    )
    description = models.CharField(
        max_length=255,
        blank=True,
        default=''
    )
    status = models.CharField(
        max_length=20,
        choices=EntityStatus.choices,
        default=EntityStatus.AI_EXTRACTED
    )

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        help_text="The ID of the user owning this project."
    )

    # --- Universal Status & Control ---
    current_stage = models.CharField(
        max_length=50,
        choices=ISPStage.choices,
        default=ISPStage.CONSULTATION,
        help_text="Current ISP phase (DEFINITION, EXPLORATION, etc.)."
    )

    agents = models.ManyToManyField(
        'agents.AgentRoleConfig',
        related_name='project',
        through='agents.AgentProjectRelation',
    )

    def __str__(self):
        return f"Project: {self.id} - Stage: {self.current_stage}"

    class Meta:
        verbose_name = "Research Project State"
        verbose_name_plural = "Research Project States"


class ChatHistoryEntry(models.Model):
    """
    Stores individual chat messages for a research project,
    matching the frontend's ChatMessage interface structure and linked to the
    overall project state.
    """

    # Role choices, corresponding to 'user' | 'system' on the frontend
    SENDER_ROLES = (
        ('user', 'User'),
        ('system', 'System/Agent'),
    )

    # Explicitly defining a UUID as the primary key (PK), matching the frontend's 'id: string'
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        help_text="Unique identifier (UUID) for the chat message, corresponding to the frontend's ID."
    )

    # --- Linkage to Project ---
    project = models.ForeignKey(
        ResearchProject,
        on_delete=models.CASCADE,
        related_name='chat_history_entries',
        help_text="Foreign key linking the message to the parent research project session."
    )

    # --- Core Message Data (Matching Frontend Interface) ---
    # The role of the sender, corresponding to the frontend's 'role'
    role = models.CharField(
        max_length=10,
        choices=SENDER_ROLES,
        help_text="The role of the sender ('user' or 'system')."
    )
    # The actual message content, corresponding to the frontend's 'content'
    content = models.TextField(
        help_text="The text content of the chat message."
    )
    # The specific name or label of the sender, corresponding to the frontend's 'name'
    name = models.CharField(
        max_length=50,
        blank=True,
        null=True,
        help_text="Specific sender identifier (e.g., username, 'Explorer Agent', 'Data Agent')."
    )

    # --- Metadata & Ordering ---
    timestamp = models.DateTimeField(
        auto_now_add=True,
        help_text="The exact time the message was recorded."
    )

    # Ensures the absolute chronological order of the messages
    sequence_number = models.IntegerField(
        help_text="The sequential order of the message within the project's history."
    )

    def __str__(self):
        return f"[{self.timestamp.strftime('%H:%M')}] {self.name} ({self.role}): {self.content[:50]}..."

    class Meta:
        verbose_name = "Chat History Entry"
        verbose_name_plural = "Chat History Entries"
        ordering = ['timestamp', 'sequence_number']


class ConsultationPhaseData(models.Model):
    """
    Data Plane Model: Stores all phase-specific outputs, metrics,
    and control variables exclusive to the CONSULTATION stage (Kuhlthau 1).
    Modified to store structured data generated by the Topic Refinement Agent.
    """

    # --- Linkage ---
    project = models.OneToOneField(
        'ResearchProject', # Use string reference if ResearchProject is defined later
        on_delete=models.CASCADE,
        primary_key=True,
        related_name='consultation_data',
        help_text="One-to-one link to the parent ResearchProject (Control Model)."
    )

    # --- LONG-TERM MEMORY & CONTROL ---
    conversation_summary = models.TextField(
        default="",
        blank=True,
        help_text="The cumulative, incremental summary of the conversation, maintained by the Summarizer Agent (Long-Term Memory)."
    )

    # Anchor for Memory Management and Data Sourcing
    last_analysis_sequence_number = models.IntegerField(
        default=0,
        help_text="The sequence number of the last chat message included in the latest structured analysis (TR Agent) or summary (SUM Agent). Serves as the checkpoint anchor for the next incremental operation."
    )

    # --- Metadata ---
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Consultation Data for Session: {self.project.project_id}"

    class Meta:
        verbose_name = "Consultation Phase Data"
        verbose_name_plural = "Consultation Phase Data"


class ExplorationPhaseData(models.Model):
    """
    Data Plane Model: Stores all phase-specific outputs, metrics,
    and control variables exclusive to the CONSULTATION stage (Kuhlthau 1).
    Modified to store structured data generated by the Topic Refinement Agent.
    """

    # --- Linkage ---
    project = models.OneToOneField(
        'ResearchProject', # Use string reference if ResearchProject is defined later
        on_delete=models.CASCADE,
        primary_key=True,
        related_name='exploration_data',
        help_text="One-to-one link to the parent ResearchProject (Control Model)."
    )

    # --- AGENT STRUCTURED OUTPUTS (Core Sidebar Data) ---
    active_canvas_id = models.UUIDField(null=True)

    # --- Metadata ---
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Exploration Data for Session: {self.project.project_id}"

    class Meta:
        verbose_name = "Exploration Phase Data"
        verbose_name_plural = "Exploration Phase Data"
