import logging
import uuid
from types import SimpleNamespace

from core.celery_app import celery_app
from django.db import transaction
from messaging.constants import PersistChatEntry, TopicStabilityUpdated
from realtime.constants import CONSULTATION_REFINED_TOPIC
from realtime.utils import send_ws_notification

from .models import (ChatHistoryEntry, ConsultationPhaseData,
                     ResearchProject)

logger = logging.getLogger(__name__)


@celery_app.task(name=PersistChatEntry.name, ignore_result=True)
def persist_chat_entry(event_type: str, payload: dict):
    """
    Celery task to asynchronously persist a single chat message entry
    to the ChatHistoryEntry database table.

    Args:
        project_id: The UUID of the Researchproject to link the message to.
        role: The sender's role ('user' or 'system').
        content: The text content of the message.
        name: The specific sender name (e.g., 'Explorer Agent').
        sequence_number: The sequential order of the message within the project.

    Returns:
        bool: True if the entry was successfully persisted, False otherwise.
    """
    task = persist_chat_entry
    project_id = payload.get('project_id')
    role = payload.get('role')
    content = payload.get('content')
    name = payload.get('name')
    sequence_number = payload.get('sequence_number')

    try:
        # Look up the ResearchProject instance
        # Retrieve the project state using the provided project_id UUID.
        project = ResearchProject.objects.get(id=uuid.UUID(project_id))
    except ResearchProject.DoesNotExist:
        # If the project state is not found, log an error and stop the task without retrying.
        logger.error(f"EntityStatus with ID {project_id} not found. Aborting chat persistence.")
        return False
    except Exception as e:
        # Handle other retrieval errors and initiate a retry mechanism.
        logger.warning(f"Error fetching EntityStatus {project_id} before persisting chat: {e}. Retrying in 60s.")
        # Retry the task after 60 seconds
        raise task.retry(exc=e, countdown=60)

    try:
        # Create and save the ChatHistoryEntry instance within an atomic transaction
        with transaction.atomic():
            ChatHistoryEntry.objects.create(
                project=project,
                role=role,
                content=content,
                name=name,
                sequence_number=sequence_number,
                # 'id' and 'timestamp' are auto-generated by the model
            )

        logger.info(f"Successfully persisted chat entry for session {project_id}, sequence {sequence_number}.")
        return True

    except Exception as e:
        # Handle persistence errors (e.g., database connection issues) and retry
        logger.error(f"Database error while persisting chat entry for session {project_id}: {e}. Retrying in 120s.")
        # Retry the task after 120 seconds.
        raise task.retry(exc=e, countdown=120)