CONSULTATION_EA_STREAM = 'consultation_ea_stream'
CONSULTATION_REFINED_TOPIC = 'consultation_refined_topic'
CONCEPTUAL_EDGES_RECOMMENDATION = 'conceptual_edges_recommendation'
CONCEPTUAL_NODES_RECOMMENDATION = 'conceptual_nodes_recommendation'
